name: Rainfall Scraper

on:
  # schedule:
  #   - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:          # allow manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas beautifulsoup4 lxml

      - name: Run scraper
        run: python rainfall_scraper.py

      - name: Commit and push updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rainfall_data.json
          git commit -m "chore: update rainfall_data.json [skip ci]" || echo "No changes to commit"
          git push
